### ISSUE TITLE
Tweet JSON format?

### ISSUE THREAD

**Issue by rsewell97** [mdredze/carmen-python#3]
Hi, this tool looks great, but I'm wondering if it is still supported?

I run the example from you API and the output is pasted below

```python
with open('test.json', 'r') as f:
    tweet_json = f.readlines(1)

tweet = json.loads(tweet_json)
resolver = carmen.get_resolver()
resolver.load_locations()
location = resolver.resolve_tweet(tweet)
print(location)
```

![image](https://user-images.githubusercontent.com/38791439/108485154-e48f6700-729c-11eb-9655-c1ec756ea79f.png)

a line from my tweet JSON file looks like this: 

```json
{
 "id": "1361068983001219000",
 "text": "sometext"
}
```

I'd greatly appreciate your help.

**Comment by AADeLucia** [comment]
Hi, thanks for checking out our tool! As of now the support is kind of limited, but we do have an update planned for the "future." 

Carmen works purely on metadata right now. So you need the entire tweet JSON and not just the ID and text.

Also, ignore the warnings. They don't mean anything useful for you.

**Comment by rsewell97** [comment]
thanks for your reply - could you point me to a Twitter endpoint which returns tweet data in a format which works with your tool?

I'm very interested in staying involved with this project, do you have a timescale for the update? I'm happy to help if necessary

**Comment by AADeLucia** [comment]
Timeline is up to my advisor (Mark Dredze). I'll let him know there's interest! 

Which Twitter endpoint did you use? If you have a list of IDs then you could also just use Hydrator https://github.com/DocNow/hydrator

**Comment by nimahassanpour** [comment]
Hi, I am using Twitter Academic Research API v2 for tweet query. Attached is a sample file I get after query (in json format not txt) . When I use Carmen to retrieve location I get None. Does Carmen support json format of this output?


[response.txt](https://github.com/mdredze/carmen-python/files/6120170/response.txt)

**Comment by AADeLucia** [comment]
Seems like you're missing a lot of metadata. And the file needs to be in JSONlines format, not just JSON. I would look into:

- [JSONlines format](https://jsonlines.readthedocs.io/en/latest/)
- [Carmen paper](https://www.aaai.org/ocs/index.php/WS/AAAIW13/paper/download/7085/6497)

**Comment by nimahassanpour** [comment]
Thank you @AADeLucia for sending over the references. I will work on them.
A quick question, what do you mean that "I am missing a lot of metadata"? Should I change my query parameters?

**Comment by nimahassanpour** [comment]
Hi @AADeLucia 
As you mentioned I provided josonline file from tweets and tried to add more meta data to it, which can be seen in the attached file (body_line.jsonl). But still I get "None" as an output of Carmen. Bellow is the code to load the jsonl file and apply Carmen for each line :

```
resolver = carmen.get_resolver()
resolver.load_locations()

with jsonlines.open('body_line.jsonl') as reader:
    for line in reader:
        print("Carmen location: ",resolver.resolve_tweet(line))
```
Can you please let me know what the problem is?


[body_line.jsonl.txt](https://github.com/mdredze/carmen-python/files/6135502/body_line.jsonl.txt)

**Comment by AADeLucia** [comment]
@nimahassanpour Carmen was written for the old Twitter API, not v2. your country info is at the top-level of the JSON, but Carmen expects that information to be under `place`. and usually the user-specified location is under `user`

https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/tweet

I haven't used the new API yet. So it just puts the requested fields in the top-level of the JSON instead of nested?
https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets#tab2

**Comment by nimahassanpour** [comment]
Thank you @AADeLucia for your reply.
Do you have a sample input file that Carmen can work properly with?
I may be able to rearrange my jsonl file in a way that Carmen can process it.

**Comment by AADeLucia** [comment]
Here's an example:
[example.txt](https://github.com/mdredze/carmen-python/files/6151343/example.txt)

And the full documentation is here:
https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/tweet

**Comment by nimahassanpour** [comment]
Thank you @AADeLucia! I really appreciate your help.

**Comment by AADeLucia** [comment]
Added API v2.0 support with Carmen 2.0 #4 #9
