### ISSUE TITLE
Add support for Twitter API v2

### ISSUE THREAD

**Issue by AADeLucia** [mdredze/carmen-python#4]
Carmen should be able to handle tweets queried with v1 and v2 API.

API v2 information: https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/place

Details below
---

@nimahassanpour Carmen was written for the old Twitter API, not v2. your country info is at the top-level of the JSON, but Carmen expects that information to be under `place`. and usually the user-specified location is under `user`

https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/tweet

I haven't used the new API yet. So it just puts the requested fields in the top-level of the JSON instead of nested?
https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets#tab2

_Originally posted by @AADeLucia in https://github.com/mdredze/carmen-python/issues/3#issuecomment-798986624_

**Comment by jackjyzhang** [comment]
- Studied Twitter API basics, compared v1.1 with v2
- Found a good way to sample lots of data (in realtime): [sampled stream](https://developer.twitter.com/en/docs/twitter-api/tweets/sampled-stream/quick-start)
- Modified geoname and place resolvers to fit new API format
- Enhanced geoname resolver by using "bbox" coordinates in `includes->places->[0]->geo->bbox`
- For the "profile" resolver, in API v2, we can only get `author_id` and we need to make an extra curl request (need Bearer token) to get the user object that contains the user location. Sounds like a bad way to do it, any workarounds?
    1. Add a merge script as a step of preprocessing to merge the twitter and user object (before actually running carmen)
    2. Check from a set of users when running carmen

Next steps:
1. Backward compatibility
2. Fix the profile resolver issue (Note that if you want to user the profile resolver with API v2, you have to make an extra curl request to get user information. Provide relevant user information in order to use the profile resolver)

**Comment by AADeLucia** [comment]
Updated with Carmen 2.0
